import 'package:kyogre_getx_lanchonete/app/burguer_app/entities/ingredientesModel.dart';

final IngredientesListaRepository = <Ingredientes>[
  Ingredientes(
    height: 30,
    type: 'picanha',
    price: 15.0,
    insertIntBurger: false,
    offset: 0,
    scale: 1,
    max: 1,
    path: 'assets/imagesBurguerApp/picanha.jpeg',
  ),
  Ingredientes(
    height: 20,
    type: 'queijo',
    price: 15.0,
    insertIntBurger: false,
    offset: -50,
    scale: 1,
    max: 5,
    path: 'assets/imagesBurguerApp/queijo.jpeg',
  ),
  Ingredientes(
    height: 50,
    type: 'tomate',
    price: -15.0,
    insertIntBurger: false,
    offset: 0,
    scale: 1,
    max: 1,
    path: 'assets/imagesBurguerApp/tomate.jpeg',
  ),
  Ingredientes(
    height: 45,
    type: 'picanha',
    price: 15.0,
    insertIntBurger: false,
    offset: 0,
    scale: 1,
    max: 1,
    path: 'assets/imagesBurguerApp/picanha.jpeg',
  ),
  Ingredientes(
    height: 45,
    type: 'bottom',
    price: 15.0,
    insertIntBurger: false,
    offset: 0,
    scale: 1,
    max: 1,
    path: 'assets/imagesBurguerApp/bottom.jpeg',
  ),
  Ingredientes(
    height: 45,
    type: 'top',
    price: 15.0,
    insertIntBurger: false,
    offset: 0,
    scale: 1,
    max: 1,
    path: 'assets/imagesBurguerApp/top.jpeg',
  ),
];
